In [8]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
x = torch.rand(2,2,2)
print(x)

tensor([[[0.1092, 0.2877],
         [0.3346, 0.5621]],

        [[0.3468, 0.0268],
         [0.4937, 0.1600]]])


## Introduction to Tensors

### Creating Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar, scalar.ndim, scalar.shape, 

(0, torch.Size([]), tensor(7))

In [ ]:
# vector
vector = torch.tensor([7.7])
vector, vector.ndim, vector.shape

(tensor([7.7000]), 1, torch.Size([1]))

In [25]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9,10]])
MATRIX, MATRIX[1], MATRIX.shape, MATRIX.ndim

(tensor([[ 7,  8],
         [ 9, 10]]),
 tensor([ 9, 10]),
 torch.Size([2, 2]),
 2)

In [31]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3], [4,5,6], [7, 8, 9]]])
TENSOR, TENSOR.ndim, TENSOR.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 3,
 torch.Size([1, 3, 3]))

### Random Tensors

Why random tensors? Neural networks initialise tensors with random data and adjust them to better represent data.

In [38]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 3, 3, 3)
random_tensor

tensor([[[[0.3478, 0.4269, 0.5097],
          [0.7949, 0.4568, 0.5523],
          [0.5491, 0.2325, 0.1627]],

         [[0.1410, 0.7776, 0.2026],
          [0.2902, 0.9564, 0.6760],
          [0.2530, 0.5852, 0.0578]],

         [[0.0614, 0.1904, 0.6139],
          [0.4099, 0.5323, 0.9206],
          [0.6166, 0.6665, 0.4051]]],


        [[[0.3201, 0.0082, 0.3964],
          [0.3311, 0.7768, 0.2907],
          [0.8414, 0.9017, 0.0705]],

         [[0.3092, 0.6817, 0.0287],
          [0.0539, 0.6596, 0.2148],
          [0.8429, 0.3417, 0.4057]],

         [[0.5903, 0.9446, 0.1981],
          [0.3517, 0.8444, 0.3161],
          [0.4075, 0.5707, 0.4147]]],


        [[[0.1466, 0.6863, 0.1460],
          [0.1526, 0.1460, 0.3912],
          [0.4474, 0.3698, 0.8433]],

         [[0.1146, 0.2835, 0.0316],
          [0.7052, 0.0745, 0.7167],
          [0.8514, 0.1994, 0.7471]],

         [[0.6232, 0.5056, 0.4288],
          [0.7923, 0.7522, 0.8340],
          [0.6648, 0.6780, 0.0672]]]])

In [35]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3)) #height, width, color channels R, G, B
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

In [39]:
# Create a tensor or all zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [40]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [41]:
ones.dtype, zeros.dtype

(torch.float32, torch.float32)

## Creating a range of tensors and tensors-like

In [49]:
# Using torch.arange
one_to_ten = torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# With step 2
one_to_ten_step2 = torch.arange(0, 10, 2)
one_to_ten_step2

tensor([0, 2, 4, 6, 8])

In [51]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [61]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [62]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [64]:
float_x_tensor = float_16_tensor * float_32_tensor
float_16_tensor.dtype

torch.float16

### Getting information from tensors

1. Tensors not the right datatype - to get datatype from a tensor, use tensor.dtype
2. Tensors not the right shape - to get shape from a tensor, use tensor.shape
3. Tensors not on the right device - to get device from a tensor, use tensor.device

In [65]:
# Create tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7151, 0.8338, 0.9438, 0.5988],
        [0.9785, 0.7065, 0.5650, 0.3623],
        [0.0356, 0.0908, 0.7729, 0.7001]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7151, 0.8338, 0.9438, 0.5988],
        [0.9785, 0.7065, 0.5650, 0.3623],
        [0.0356, 0.0908, 0.7729, 0.7001]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu
